baseURL: "https://tanulsingh.github.io/public" 
title: Mr. KnowNothing
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv.pdf
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Personal Projects
          url: projects/
          weight: 3
        - name: Archive
          url: archive/
          weight: 4

params:
    description: ""
    author: Tanul Singh
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    #MainSections: ["CV","blogs","projects","Archive"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tanul Singh
          subtitle: "I am a Lead Machine Learning Engineer with 4 years of experience primarily working in the field of NLP,
          LLMs and GenAI. I have a proven track record of building NLP systems, training and deploying Large Language models at scale.
          "
          imageUrl: "402A2908.JPG"
          imageWidth: 160
          imageHeight: 155
          imageTitle: Tanul Singh
          buttons:
            - name: CV
              url: cv.pdf
            - name: Blog
              url: posts/
            - name: Personal Projects
              url: projects/
            - name: Archive
              url: archive/

    socialIcons:
        - name: GitHub
          url: https://github.com/tanulsingh
        - name: LinkedIn
          url: https://www.linkedin.com/in/tanul-singh/
        - name: Kaggle
          url: https://www.kaggle.com/tanulsingh077
        - name: Twitter
          url: https://x.com/singh_tanul
        - name: Email
          url: mailto:tanulsingh0077@gmail.com
        

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Tanul Singh"
      icon: 402A2908.JPG
      iconHeight: 20

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: dracula 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2